[package]
name = "simpleblog"
version = "0.1.0"
edition = "2021"

[dependencies]
poem = {version = "3.1.0", features = ["static-files"]}
tokio = {version = "1.40.0", features = ["rt-multi-thread"]}
http = "1.1.0"
markdown = "0.3.0"
serde_yml = "0.0.12"
serde = "1.0.210"