file_path : C:\Users\defue\Documents\PersonalProjects\GenPrograming\Active\simpleblog\simpleblog\simpleblog\
site_title : Sample Blog Site
site_description : A Sample Blog Website
site_link: http://localhost:3000
admin_username: Username
admin_password: Password
port: 127.0.0.1:3000